#!/usr/bin/env python3

import os
import sys
import mmap
import json
import argparse
from os.path import basename, isfile, join, dirname

parser = argparse.ArgumentParser(prog=basename(sys.argv[0]), description="alfred+nvalt integration")
parser.add_argument("-d", "--dir", required=True, help="nvalt storage path")
parser.add_argument("search", nargs="+", help="search term")

args = parser.parse_args()

terms = [x.strip() for x in " ".join(args.search).split(" ") if len(x.strip()) > 0]
results = []

for root, _, files in os.walk(args.dir):
    for file in files:
        path = os.path.join(root, file)
        with open(path, mode="r") as f:
            with mmap.mmap(f.fileno(), length=0, access=mmap.ACCESS_READ) as o:
                buf = str(o.read()).lower()
                if all([s.lower() in buf for s in terms]):
                    results.append({
                        "title": os.path.splitext(file)[0],
                        "arg": path
                    })

print(json.dumps({"items": results}))
